# -*- coding: utf-8 -*-
"""lab-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSkcJ7OAUYk9GmbNv5RIkbjGDcOXXk3l
"""

# from google.colab import drive
# drive.mount('/content/drive')